server:
  port: 30001
spring:
  dubbo:
    application:
      name: dubbo-spring-boot-provider
    scan: art.redoc.provider
    registry:
      address: ${ZOOKEEPER_SERVER:127.0.0.1}
      port: 30000
      protocol: zookeeper
      register: true
    protocol:
      name: dubbo
      port: 20880

