version: "2"
services:
  zookeeper:
    image: 'registry.aliyuncs.com/acs-sample/zookeeper:3.4.8'
    hostname: zookeeper
  provider:
    image: 'registry.cn-beijing.aliyuncs.com/redoc/dubbo-springboot-provider:0.1.0'
    environment:
      - ZOOKEEPER_SERVER=zookeeper
  consumer:
    image: 'registry.cn-beijing.aliyuncs.com/redoc/dubbo-springboot-consumer:0.1.0'
    environment:
      - ZOOKEEPER_SERVER=zookeeper
    ports:
      - 30000:30000
